<?php

namespace Chebur\DBALSphinx\Platforms;

use Chebur\DBALSphinx\Platforms\Keywords\SphinxKeywords;
use Doctrine\DBAL\DBALException;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Platforms\TrimMode;
use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\ColumnDiff;
use Doctrine\DBAL\Schema\Constraint;
use Doctrine\DBAL\Schema\ForeignKeyConstraint;
use Doctrine\DBAL\Schema\Identifier;
use Doctrine\DBAL\Schema\Index;
use Doctrine\DBAL\Schema\Sequence;
use Doctrine\DBAL\Schema\Table;
use Doctrine\DBAL\Schema\TableDiff;
use Doctrine\DBAL\Types\Type;

//class SphinxPlatform extends MySqlPlatform
class SphinxPlatform extends AbstractPlatform
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'sphinx';
    }

    /**
     * {@inheritDoc}
     */
    protected function getReservedKeywordsClass()
    {
        return SphinxKeywords::class;
    }

    /**
     * @inheritDoc
     */
    public function getBooleanTypeDeclarationSQL(array $columnDef)
    {
        // TODO: Implement getBooleanTypeDeclarationSQL() method.
    }

    /**
     * @inheritDoc
     */
    public function getIntegerTypeDeclarationSQL(array $columnDef)
    {
        // TODO: Implement getIntegerTypeDeclarationSQL() method.
    }

    /**
     * @inheritDoc
     */
    public function getBigIntTypeDeclarationSQL(array $columnDef)
    {
        // TODO: Implement getBigIntTypeDeclarationSQL() method.
    }

    /**
     * @inheritDoc
     */
    public function getSmallIntTypeDeclarationSQL(array $columnDef)
    {
        // TODO: Implement getSmallIntTypeDeclarationSQL() method.
    }

    /**
     * @inheritDoc
     */
    protected function _getCommonIntegerTypeDeclarationSQL(array $columnDef)
    {
        // TODO: Implement _getCommonIntegerTypeDeclarationSQL() method.
    }

    /**
     * @inheritDoc
     */
    public function getClobTypeDeclarationSQL(array $field)
    {
        // TODO: Implement getClobTypeDeclarationSQL() method.
    }

    /**
     * @inheritDoc
     */
    public function getBlobTypeDeclarationSQL(array $field)
    {
        // TODO: Implement getBlobTypeDeclarationSQL() method.
    }

    /**
     * @inheritDoc
     */
    public function getVarcharTypeDeclarationSQL(array $field)
    {
        return parent::getVarcharTypeDeclarationSQL($field); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getBinaryTypeDeclarationSQL(array $field)
    {
        return parent::getBinaryTypeDeclarationSQL($field); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getGuidTypeDeclarationSQL(array $field)
    {
        return parent::getGuidTypeDeclarationSQL($field); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getJsonTypeDeclarationSQL(array $field)
    {
        return parent::getJsonTypeDeclarationSQL($field); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getVarcharTypeDeclarationSQLSnippet($length, $fixed)
    {
        parent::getVarcharTypeDeclarationSQLSnippet($length, $fixed); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getBinaryTypeDeclarationSQLSnippet($length, $fixed)
    {
        parent::getBinaryTypeDeclarationSQLSnippet($length, $fixed); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function initializeDoctrineTypeMappings()
    {
        // TODO: Implement initializeDoctrineTypeMappings() method.
    }

    /**
     * @inheritDoc
     */
    public function registerDoctrineTypeMapping($dbType, $doctrineType)
    {
        parent::registerDoctrineTypeMapping($dbType, $doctrineType); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDoctrineTypeMapping($dbType)
    {
        return parent::getDoctrineTypeMapping($dbType); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function hasDoctrineTypeMappingFor($dbType)
    {
        return parent::hasDoctrineTypeMappingFor($dbType); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function initializeCommentedDoctrineTypes()
    {
        parent::initializeCommentedDoctrineTypes(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function isCommentedDoctrineType(Type $doctrineType)
    {
        return parent::isCommentedDoctrineType($doctrineType); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function markDoctrineTypeCommented($doctrineType)
    {
        parent::markDoctrineTypeCommented($doctrineType); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDoctrineTypeComment(Type $doctrineType)
    {
        return parent::getDoctrineTypeComment($doctrineType); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getColumnComment(Column $column)
    {
        return parent::getColumnComment($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getIdentifierQuoteCharacter()
    {
        return parent::getIdentifierQuoteCharacter(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getSqlCommentStartString()
    {
        return parent::getSqlCommentStartString(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getSqlCommentEndString()
    {
        return parent::getSqlCommentEndString(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getVarcharMaxLength()
    {
        return parent::getVarcharMaxLength(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getVarcharDefaultLength()
    {
        return parent::getVarcharDefaultLength(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getBinaryMaxLength()
    {
        return parent::getBinaryMaxLength(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getBinaryDefaultLength()
    {
        return parent::getBinaryDefaultLength(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getWildcards()
    {
        return parent::getWildcards(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getRegexpExpression()
    {
        parent::getRegexpExpression(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getGuidExpression()
    {
        parent::getGuidExpression(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getAvgExpression($column)
    {
        return parent::getAvgExpression($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCountExpression($column)
    {
        return parent::getCountExpression($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getMaxExpression($column)
    {
        return parent::getMaxExpression($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getMinExpression($column)
    {
        return parent::getMinExpression($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getSumExpression($column)
    {
        return parent::getSumExpression($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getMd5Expression($column)
    {
        return parent::getMd5Expression($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getLengthExpression($column)
    {
        return parent::getLengthExpression($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getSqrtExpression($column)
    {
        return parent::getSqrtExpression($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getRoundExpression($column, $decimals = 0)
    {
        return parent::getRoundExpression($column, $decimals); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getModExpression($expression1, $expression2)
    {
        return parent::getModExpression($expression1, $expression2); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getTrimExpression($str, $mode = TrimMode::UNSPECIFIED, $char = false)
    {
        return parent::getTrimExpression($str, $mode, $char); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getRtrimExpression($str)
    {
        return parent::getRtrimExpression($str); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getLtrimExpression($str)
    {
        return parent::getLtrimExpression($str); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getUpperExpression($str)
    {
        return parent::getUpperExpression($str); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getLowerExpression($str)
    {
        return parent::getLowerExpression($str); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getLocateExpression($str, $substr, $startPos = false)
    {
        parent::getLocateExpression($str, $substr, $startPos); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getNowExpression()
    {
        return parent::getNowExpression(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getSubstringExpression($value, $from, $length = null)
    {
        return parent::getSubstringExpression($value, $from, $length); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getConcatExpression()
    {
        return parent::getConcatExpression(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getNotExpression($expression)
    {
        return parent::getNotExpression($expression); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getIsNullExpression($expression)
    {
        return parent::getIsNullExpression($expression); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getIsNotNullExpression($expression)
    {
        return parent::getIsNotNullExpression($expression); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getBetweenExpression($expression, $value1, $value2)
    {
        return parent::getBetweenExpression($expression, $value1, $value2); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getAcosExpression($value)
    {
        return parent::getAcosExpression($value); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getSinExpression($value)
    {
        return parent::getSinExpression($value); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getPiExpression()
    {
        return parent::getPiExpression(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCosExpression($value)
    {
        return parent::getCosExpression($value); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateDiffExpression($date1, $date2)
    {
        parent::getDateDiffExpression($date1, $date2); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateAddSecondsExpression($date, $seconds)
    {
        return parent::getDateAddSecondsExpression($date, $seconds); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateSubSecondsExpression($date, $seconds)
    {
        return parent::getDateSubSecondsExpression($date, $seconds); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateAddMinutesExpression($date, $minutes)
    {
        return parent::getDateAddMinutesExpression($date, $minutes); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateSubMinutesExpression($date, $minutes)
    {
        return parent::getDateSubMinutesExpression($date, $minutes); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateAddHourExpression($date, $hours)
    {
        return parent::getDateAddHourExpression($date, $hours); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateSubHourExpression($date, $hours)
    {
        return parent::getDateSubHourExpression($date, $hours); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateAddDaysExpression($date, $days)
    {
        return parent::getDateAddDaysExpression($date, $days); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateSubDaysExpression($date, $days)
    {
        return parent::getDateSubDaysExpression($date, $days); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateAddWeeksExpression($date, $weeks)
    {
        return parent::getDateAddWeeksExpression($date, $weeks); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateSubWeeksExpression($date, $weeks)
    {
        return parent::getDateSubWeeksExpression($date, $weeks); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateAddMonthExpression($date, $months)
    {
        return parent::getDateAddMonthExpression($date, $months); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateSubMonthExpression($date, $months)
    {
        return parent::getDateSubMonthExpression($date, $months); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateAddQuartersExpression($date, $quarters)
    {
        return parent::getDateAddQuartersExpression($date, $quarters); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateSubQuartersExpression($date, $quarters)
    {
        return parent::getDateSubQuartersExpression($date, $quarters); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateAddYearsExpression($date, $years)
    {
        return parent::getDateAddYearsExpression($date, $years); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateSubYearsExpression($date, $years)
    {
        return parent::getDateSubYearsExpression($date, $years); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getDateArithmeticIntervalExpression($date, $operator, $interval, $unit)
    {
        parent::getDateArithmeticIntervalExpression(
            $date,
            $operator,
            $interval,
            $unit
        ); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getBitAndComparisonExpression($value1, $value2)
    {
        return parent::getBitAndComparisonExpression($value1, $value2); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getBitOrComparisonExpression($value1, $value2)
    {
        return parent::getBitOrComparisonExpression($value1, $value2); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getForUpdateSQL()
    {
        return parent::getForUpdateSQL(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function appendLockHint($fromClause, $lockMode)
    {
        return parent::appendLockHint($fromClause, $lockMode); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getReadLockSQL()
    {
        return parent::getReadLockSQL(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getWriteLockSQL()
    {
        return parent::getWriteLockSQL(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDropDatabaseSQL($database)
    {
        DBALException::notSupported(__METHOD__);
    }

    /**
     * @inheritDoc
     */
    public function getDropTableSQL($table)
    {
        DBALException::notSupported(__METHOD__);
    }

    /**
     * @inheritDoc
     */
    public function getDropTemporaryTableSQL($table)
    {
        DBALException::notSupported(__METHOD__);
    }

    /**
     * @inheritDoc
     */
    public function getDropIndexSQL($index, $table = null)
    {
        DBALException::notSupported(__METHOD__);
    }

    /**
     * @inheritDoc
     */
    public function getDropConstraintSQL($constraint, $table)
    {
        return parent::getDropConstraintSQL($constraint, $table); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDropForeignKeySQL($foreignKey, $table)
    {
        return parent::getDropForeignKeySQL($foreignKey, $table); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateTableSQL(Table $table, $createFlags = self::CREATE_INDEXES)
    {
        return parent::getCreateTableSQL($table, $createFlags); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCommentOnColumnSQL($tableName, $columnName, $comment)
    {
        return parent::getCommentOnColumnSQL($tableName, $columnName, $comment); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getInlineColumnCommentSQL($comment)
    {
        return parent::getInlineColumnCommentSQL($comment); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function _getCreateTableSQL($tableName, array $columns, array $options = [])
    {
        return parent::_getCreateTableSQL($tableName, $columns, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateTemporaryTableSnippetSQL()
    {
        return parent::getCreateTemporaryTableSnippetSQL(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateSequenceSQL(Sequence $sequence)
    {
        parent::getCreateSequenceSQL($sequence); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getAlterSequenceSQL(Sequence $sequence)
    {
        parent::getAlterSequenceSQL($sequence); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateConstraintSQL(Constraint $constraint, $table)
    {
        return parent::getCreateConstraintSQL($constraint, $table); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateIndexSQL(Index $index, $table)
    {
        return parent::getCreateIndexSQL($index, $table); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getPartialIndexSQL(Index $index)
    {
        return parent::getPartialIndexSQL($index); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getCreateIndexSQLFlags(Index $index)
    {
        return parent::getCreateIndexSQLFlags($index); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreatePrimaryKeySQL(Index $index, $table)
    {
        return parent::getCreatePrimaryKeySQL($index, $table); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateSchemaSQL($schemaName)
    {
        parent::getCreateSchemaSQL($schemaName); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function quoteIdentifier($str)
    {
        return parent::quoteIdentifier($str); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function quoteSingleIdentifier($str)
    {
        return parent::quoteSingleIdentifier($str); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateForeignKeySQL(ForeignKeyConstraint $foreignKey, $table)
    {
        return parent::getCreateForeignKeySQL($foreignKey, $table); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getAlterTableSQL(TableDiff $diff)
    {
        parent::getAlterTableSQL($diff); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function onSchemaAlterTableAddColumn(Column $column, TableDiff $diff, &$columnSql)
    {
        return parent::onSchemaAlterTableAddColumn($column, $diff, $columnSql); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function onSchemaAlterTableRemoveColumn(Column $column, TableDiff $diff, &$columnSql)
    {
        return parent::onSchemaAlterTableRemoveColumn(
            $column,
            $diff,
            $columnSql
        ); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function onSchemaAlterTableChangeColumn(ColumnDiff $columnDiff, TableDiff $diff, &$columnSql)
    {
        return parent::onSchemaAlterTableChangeColumn(
            $columnDiff,
            $diff,
            $columnSql
        ); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function onSchemaAlterTableRenameColumn($oldColumnName, Column $column, TableDiff $diff, &$columnSql)
    {
        return parent::onSchemaAlterTableRenameColumn(
            $oldColumnName,
            $column,
            $diff,
            $columnSql
        ); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function onSchemaAlterTable(TableDiff $diff, &$sql)
    {
        return parent::onSchemaAlterTable($diff, $sql); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getPreAlterTableIndexForeignKeySQL(TableDiff $diff)
    {
        return parent::getPreAlterTableIndexForeignKeySQL($diff); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getPostAlterTableIndexForeignKeySQL(TableDiff $diff)
    {
        return parent::getPostAlterTableIndexForeignKeySQL($diff); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function getRenameIndexSQL($oldIndexName, Index $index, $tableName)
    {
        return parent::getRenameIndexSQL($oldIndexName, $index, $tableName); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function _getAlterTableIndexForeignKeySQL(TableDiff $diff)
    {
        return parent::_getAlterTableIndexForeignKeySQL($diff); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getColumnDeclarationListSQL(array $fields)
    {
        return parent::getColumnDeclarationListSQL($fields); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getColumnDeclarationSQL($name, array $field)
    {
        return parent::getColumnDeclarationSQL($name, $field); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDecimalTypeDeclarationSQL(array $columnDef)
    {
        return parent::getDecimalTypeDeclarationSQL($columnDef); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDefaultValueDeclarationSQL($field)
    {
        return parent::getDefaultValueDeclarationSQL($field); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCheckDeclarationSQL(array $definition)
    {
        return parent::getCheckDeclarationSQL($definition); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getUniqueConstraintDeclarationSQL($name, Index $index)
    {
        return parent::getUniqueConstraintDeclarationSQL($name, $index); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getIndexDeclarationSQL($name, Index $index)
    {
        return parent::getIndexDeclarationSQL($name, $index); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCustomTypeDeclarationSQL(array $columnDef)
    {
        return parent::getCustomTypeDeclarationSQL($columnDef); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getIndexFieldDeclarationListSQL(array $fields)
    {
        return parent::getIndexFieldDeclarationListSQL($fields); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getTemporaryTableSQL()
    {
        return parent::getTemporaryTableSQL(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getTemporaryTableName($tableName)
    {
        return parent::getTemporaryTableName($tableName); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getForeignKeyDeclarationSQL(ForeignKeyConstraint $foreignKey)
    {
        return parent::getForeignKeyDeclarationSQL($foreignKey); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getAdvancedForeignKeyOptionsSQL(ForeignKeyConstraint $foreignKey)
    {
        return parent::getAdvancedForeignKeyOptionsSQL($foreignKey); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getForeignKeyReferentialActionSQL($action)
    {
        return parent::getForeignKeyReferentialActionSQL($action); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getForeignKeyBaseDeclarationSQL(ForeignKeyConstraint $foreignKey)
    {
        return parent::getForeignKeyBaseDeclarationSQL($foreignKey); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getUniqueFieldDeclarationSQL()
    {
        return parent::getUniqueFieldDeclarationSQL(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getColumnCharsetDeclarationSQL($charset)
    {
        return parent::getColumnCharsetDeclarationSQL($charset); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function prefersSequences()
    {
        return parent::prefersSequences(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function prefersIdentityColumns()
    {
        return parent::prefersIdentityColumns(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function convertBooleans($item)
    {
        return parent::convertBooleans($item); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function convertFromBoolean($item)
    {
        return parent::convertFromBoolean($item); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function convertBooleansToDatabaseValue($item)
    {
        return parent::convertBooleansToDatabaseValue($item); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCurrentDateSQL()
    {
        throw DBALException::notSupported(__METHOD__);
    }

    /**
     * @inheritDoc
     */
    public function getCurrentTimeSQL()
    {
        throw DBALException::notSupported(__METHOD__);
    }

    /**
     * @inheritDoc
     */
    public function getCurrentTimestampSQL()
    {
        throw DBALException::notSupported(__METHOD__);
    }

    /**
     * http://sphinxsearch.com/docs/current.html#sphinxql-show-databases
     * @inheritDoc
     */
    public function getListDatabasesSQL()
    {
        return 'SHOW DATABASES'; //supported, but does absolutely nothing
    }

    /**
     * http://sphinxsearch.com/docs/current.html#sphinxql-describe
     * @inheritDoc
     */
    public function getListTableColumnsSQL($table, $database = null)
    {
        //return 'DESC '.$table;
        return 'DESCRIBE '.$table;
    }

    /**
     * http://sphinxsearch.com/docs/current.html#sphinxql-show-tables
     * @inheritDoc
     */
    public function getListTablesSQL()
    {
        return 'SHOW TABLES';
    }

    /**
     * @inheritDoc
     */
    public function getListViewsSQL($database)
    {
        parent::getListViewsSQL($database); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getListTableIndexesSQL($table, $currentDatabase = null)
    {
        parent::getListTableIndexesSQL($table, $currentDatabase); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getListTableForeignKeysSQL($table)
    {
        parent::getListTableForeignKeysSQL($table); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateViewSQL($name, $sql)
    {
        parent::getCreateViewSQL($name, $sql); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDropViewSQL($name)
    {
        parent::getDropViewSQL($name); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDropSequenceSQL($sequence)
    {
        parent::getDropSequenceSQL($sequence); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getSequenceNextValSQL($sequenceName)
    {
        parent::getSequenceNextValSQL($sequenceName); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getCreateDatabaseSQL($database)
    {
        parent::getCreateDatabaseSQL($database); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getSetTransactionIsolationSQL($level)
    {
        parent::getSetTransactionIsolationSQL($level); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateTimeTypeDeclarationSQL(array $fieldDeclaration)
    {
        parent::getDateTimeTypeDeclarationSQL($fieldDeclaration); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateTimeTzTypeDeclarationSQL(array $fieldDeclaration)
    {
        return parent::getDateTimeTzTypeDeclarationSQL($fieldDeclaration); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateTypeDeclarationSQL(array $fieldDeclaration)
    {
        parent::getDateTypeDeclarationSQL($fieldDeclaration); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getTimeTypeDeclarationSQL(array $fieldDeclaration)
    {
        parent::getTimeTypeDeclarationSQL($fieldDeclaration); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getFloatDeclarationSQL(array $fieldDeclaration)
    {
        return parent::getFloatDeclarationSQL($fieldDeclaration); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDefaultTransactionIsolationLevel()
    {
        return parent::getDefaultTransactionIsolationLevel(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function supportsSequences()
    {
        return parent::supportsSequences(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function supportsIdentityColumns()
    {
        return parent::supportsIdentityColumns(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function usesSequenceEmulatedIdentityColumns()
    {
        return parent::usesSequenceEmulatedIdentityColumns(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getIdentitySequenceName($tableName, $columnName)
    {
        parent::getIdentitySequenceName($tableName, $columnName); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function supportsIndexes()
    {
        return false;
    }

    /**
     * @inheritDoc
     */
    public function supportsSavepoints()
    {
        return false;
    }

    /**
     * @inheritDoc
     */
    public function supportsPrimaryConstraints()
    {
        return parent::supportsPrimaryConstraints(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function supportsForeignKeyConstraints()
    {
        return false;
    }

    /**
     * @inheritDoc
     */
    public function supportsCreateDropDatabase()
    {
        return false;
    }

    /**
     * @inheritDoc
     */
    public function hasNativeJsonType()
    {
        return true;
    }

    /**
     * @inheritDoc
     */
    public function getIdentityColumnNullInsertSQL()
    {
        return parent::getIdentityColumnNullInsertSQL(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function supportsViews()
    {
        return false;
    }

    /**
     * @inheritDoc
     */
    public function getDateTimeFormatString()
    {
        return parent::getDateTimeFormatString(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateTimeTzFormatString()
    {
        return parent::getDateTimeTzFormatString(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getDateFormatString()
    {
        return parent::getDateFormatString(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getTimeFormatString()
    {
        return parent::getTimeFormatString(); // TODO: Change the autogenerated stub
    }

    /**
     * http://sphinxsearch.com/docs/current.html#sphinxql-select
     * @inheritDoc
     */
    protected function doModifyLimitQuery($query, $limit, $offset)
    {
        if ($limit === null) {
            $limit = PHP_INT_MAX - 1;
        }
        if ($offset === null) {
            $offset = 0;
        }
        $query .= 'LIMIT '.$limit.', '.$offset;

        return $query;
    }

    /**
     * @inheritDoc
     */
    public function getSQLResultCasing($column)
    {
        return parent::getSQLResultCasing($column); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function fixSchemaElementName($schemaElementName)
    {
        return parent::fixSchemaElementName($schemaElementName); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getMaxIdentifierLength()
    {
        return parent::getMaxIdentifierLength(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getEmptyIdentityInsertSQL($tableName, $identifierColumnName)
    {
        return parent::getEmptyIdentityInsertSQL(
            $tableName,
            $identifierColumnName
        ); // TODO: Change the autogenerated stub
    }

    /**
     * http://sphinxsearch.com/docs/current.html#sphinxql-truncate-rtindex
     * @inheritDoc
     */
    public function getTruncateTableSQL($tableName, $cascade = false)
    {
        $tableIdentifier = new Identifier($tableName);

        return 'TRUNCATE RTINDEX ' . $tableIdentifier->getQuotedName($this);
    }

    /**
     * @inheritDoc
     */
    public function createSavePoint($savepoint)
    {
        return parent::createSavePoint($savepoint); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function releaseSavePoint($savepoint)
    {
        return parent::releaseSavePoint($savepoint); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function rollbackSavePoint($savepoint)
    {
        return parent::rollbackSavePoint($savepoint); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function quoteStringLiteral($str)
    {
        return parent::quoteStringLiteral($str); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getStringLiteralQuoteCharacter()
    {
        return parent::getStringLiteralQuoteCharacter(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    protected function getLikeWildcardCharacters(): string
    {
        return parent::getLikeWildcardCharacters(); // TODO: Change the autogenerated stub
    }

}
